Small Fix
JuliaSmoothOptimizers/AdaptiveRegularization.jl pull request #120
Opened 2024-07-23 17:33 UTC by nrummel

Hello JSO Team,
 
I wanted to use your ARCqK algorithm in my work, but it was cycling when my cost function was misbehaving. I think the algorithm is supposed to exit when there are too many unsuccessful iterations in a row, but instead it got stuck in an infinite loop until time controls hit.
Also, I want to pass the nlp_at_x the callback so that I have access to the current x at each iteration. 
Finally, I think the counter for very successful iterations was in the wrong place. 

Thanks for making your algorithm available in Julia.
Nic

2024-07-24 21:45 UTC, tmigot commented
Hi @nrummel ! Thanks for the PR, I think this is connect to this issue: https://github.com/JuliaSmoothOptimizers/AdaptiveRegularization.jl/issues/84

2024-07-24 22:00 UTC, tmigot requested changes
Thanks for the PR @nrummel ! There are still improvements that can be made to this algorithm, so thank you for testing and contributing.

I made some comments, but overall it looks good.

2024-07-24 22:00 UTC, tmigot commented on src/main.jl
> -  callback(nlp, solver, stats)
You can actually access the nlp_at_x by solver.stp.nlp_at_x , so I prefer `callback(nlp, solver, stats)`

2024-07-24 22:00 UTC, tmigot commented on src/main.jl
> +  callback(nlp_at_x, solver, stats)
```suggestion
  callback(nlp, solver, stats)
```

2024-07-24 22:00 UTC, tmigot commented on src/main.jl
> +    callback(nlp_at_x, solver, stats)
```suggestion
    callback(nlp, solver, stats)
```

2024-07-24 22:00 UTC, tmigot commented on src/main.jl
> +          verysucc += 1 # TODO: check if this makes sense
```suggestion
          verysucc += 1
```
looks good, thanks

2024-07-24 22:00 UTC, tmigot commented on src/main.jl
> +      # don't just cycle if we have to many unsucessful iterations
I don' think the scenario, `success = true` and `unsuccinarow >= max_unsuccinarow` is possible.
```suggestion
    if unsuccinarow >= max_unsuccinarow
```

2024-08-28 19:54 UTC, nrummel commented
I still am not seeing the remote/main having these changes. It would be nice if this was merged into main, so I don't have to dev this repo anymore. Thanks again. Nic

2024-09-01 08:27 UTC, tmigot commented
Hi @nrummel ! As you can see here, I made some comments that you need to adress before the PR is being merged.

2024-09-15 00:40 UTC, merged

2024-09-17 14:22 UTC, nrummel commented
Thanks for doing this. Apologies, I have been pushing this small task down my to do list for a while now.